# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20170807_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionstatus',
            name='when',
            field=models.DateTimeField(),
        ),
    ]
