# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_transactionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionstatus',
            name='when',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=b'date created'),
            preserve_default=False,
        ),
    ]
