# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiterappbackend', '0005_auto_20170807_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionstatus',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
